# Generated by Django 2.2.5 on 2019-09-10 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_auto_20190909_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='days',
            old_name='day',
            new_name='days',
        ),
    ]
