# Generated by Django 2.2.5 on 2019-09-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_auto_20190909_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='day',
        ),
        migrations.AddField(
            model_name='kitchen',
            name='day',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], default=2, max_length=8),
            preserve_default=False,
        ),
    ]
