# Generated by Django 2.2.5 on 2019-09-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_auto_20190909_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='day',
        ),
        migrations.AddField(
            model_name='kitchen',
            name='day',
            field=models.ManyToManyField(to='kitchen.Days'),
        ),
    ]
