# Generated by Django 2.2.5 on 2019-09-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0009_delete_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='kitchen',
            name='day',
        ),
        migrations.AddField(
            model_name='kitchen',
            name='day',
            field=models.ManyToManyField(to='kitchen.Days'),
        ),
    ]
